### ISSUE TITLE
Envio de Comando Atualizar pelo SPV para reiniciar o ANAQ com erro

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/ANAQ_2017#11]
Envio de Comando Atualizar pelo SPV para reiniciar o ANAQ com erro

![whatsapp image 2018-05-15 at 14 48 13](https://user-images.githubusercontent.com/39096287/40074367-cf17ca3a-584f-11e8-8825-3c8382a65858.jpeg)

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SPV] RabbitMQ: Envio de Comando Atualizar pelo SPV para reiniciar o ANAQ com erro](https://trello.com/c/IieahZ5F/17-spv-rabbitmq-envio-de-comando-atualizar-pelo-spv-para-reiniciar-o-anaq-com-erro)

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CPFL] Envio de comando de atualização do ANAQ pelo SPV causa erro](https://trello.com/c/6j4qb00l/34-cpfl-envio-de-comando-de-atualiza%C3%A7%C3%A3o-do-anaq-pelo-spv-causa-erro)

**Comment by felipe-coutto** [comment]
Atualização desabilitada através do registro do Windows:
Chave SOFTWARE \ ANAQ 
Valor DesabilitaAtualizacaoANAQ deve ser definido como 1 para impedir envio de atualização para as instâncias
