### ISSUE TITLE
[CPFL] Plano Alto - Problema de sincronização de blocos no osciloscópio

### ISSUE THREAD

**Issue by fernandocsmd** [md-monitoracao-diagnose/ANAQ_2017#12]
![image](https://user-images.githubusercontent.com/42279122/43972269-29b75e8a-9caa-11e8-916e-dba0f70eb021.png)

![image](https://user-images.githubusercontent.com/42279122/43972325-5bb4ceae-9caa-11e8-97e0-5c8dfa6bcf96.png)

**Comment by CemachMD** [comment]
Problema resolvido após implementação da nova estratégia de comunicação entre usinas e CMA
