### ISSUE TITLE
[cpfl pch044] Erro ao salvar no dispositivo_HMI

### ISSUE THREAD

**Issue by fernandocsmd** [md-monitoracao-diagnose/ANAQ_2017#13]
Ao mudar a taxa de aquisição de baixa no hmi de Ludesa, mandando salvar no dispositvo, aparece o seguinte erro:

![image](https://user-images.githubusercontent.com/42279122/44034982-c9d260f4-9ee4-11e8-87e7-22a376a505a6.png)

**Comment by felipe-coutto** [comment]
@fernandocsmd O cRIO de Ludesa está realizando testes de comunicação com o SDSC e não está com todas as funcionalidades do SPV rodando, então este problema é esperado. Quanto terminar de realizar os testes eu te aviso para que você realize a atualização.
