### ISSUE TITLE
Parâmetros de Identificador de Parada de Maquina não são enviados corretamente

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/ANAQ_2017#6]
O Valor Superior e Inferior configurado pelo Configurator.exe nao aplica corretamente no destino (Ludesa)

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CPFL] Problemas de comunicação e aquisição #surpresa](https://trello.com/c/bmW55qa6/24-cpfl-problemas-de-comunica%C3%A7%C3%A3o-e-aquisi%C3%A7%C3%A3o-surpresa)

**Comment by felipe-coutto** [comment]
Atualização foi feita na gerdaq.dll para que os valores superiores e inferiores fossem enviados corretamente. DLL atualizada no CMA.
