### ISSUE TITLE
Não existe Interface de Configuração para Gravação por Trigger

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/ANAQ_2017#8]
Não existe Interface de Configuração para Gravação por Trigger, a principio esta interface deveria estar no Configurator, considerando que o Flag de habilitação pode-se ser encontrado no ANAQ_CONFIG.

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[ANAQ] Criar interface de configuração para uso de Trigger](https://trello.com/c/iDN2ideb/24-anaq-criar-interface-de-configura%C3%A7%C3%A3o-para-uso-de-trigger)
